name: Build containers

on:
  push:
    branches:
      - main
      - release

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build docker containers
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          TAG: ${{ github.sha }}
        run: |
          docker-compose --file=docker-compose.k8s.yml build \
            --build-arg BRANCH=${{ steps.extract_branch.outputs.branch }} \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache,mode=max \
            frontend \
            frontend-sidecar \
            nginx \
            php

     
